name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      - run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{ secrets.TOKEN }}
      - run: docker build -t ghcr.io/$REPO:latest -t ghcr.io/vorishka-bot:$GITHUB_SHA .
      - run: docker image push ghcr.io/$REPO:$GITHUB_SHA
      - run: docker image push ghcr.io/$REPO:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    env:
      TARGET_PATH: ${{ secrets.REMOTE_PATH }}
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
      - run: scp -o StrictHostKeyChecking=no -i private_key docker-compose.production.yml ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_SERVER }}:$TARGET_PATH
      - run: |
          ssh -T -o StrictHostKeyChecking=no -i private_key ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_SERVER }} <<EOF
            cd $TARGET_PATH
            docker login ghcr.io -u $GITHUB_ACTOR -p ${{ secrets.TOKEN }}
            docker pull ghcr.io/$REPO:$GITHUB_SHA
            docker-compose -f docker-compose.production.yml up -d
            docker system prune --all --force
          EOF
      - run: rm -f private_key
